[package]
name = "web_crawler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.2"
native-tls = "0.2.11"
flate2 = "1.0"
regex = "1.5.4"
log = "0.4.21"
